"""
Mock signals for Demo Mode — no API key required.
Simulates realistic output from the LLM extraction pipeline.
"""
from datetime import datetime, timedelta
import random

RAW_MOCK_SIGNALS = [
    {
        "ticker": "NVDA",
        "asset_type": "stock",
        "event_type": "earnings",
        "sentiment": 0.88,
        "magnitude": 9,
        "time_sensitivity": "immediate",
        "confidence": 0.94,
        "summary": "NVIDIA posts record Q4 revenue of $22.1B, up 265% YoY. Data center segment beats estimates by 18%, driven by H100 GPU demand.",
        "key_phrases": ["record revenue", "265% YoY growth", "data center beats", "H100 demand surge"],
        "source_title": "NVIDIA Q4 2024 Earnings Release",
        "source_url": "https://investor.nvidia.com/earnings",
    },
    {
        "ticker": "BTC-USD",
        "asset_type": "crypto",
        "event_type": "macro",
        "sentiment": 0.72,
        "magnitude": 8,
        "time_sensitivity": "immediate",
        "confidence": 0.87,
        "summary": "SEC approves spot Bitcoin ETF applications from BlackRock and Fidelity. Historic milestone opens institutional floodgates.",
        "key_phrases": ["SEC approves", "spot Bitcoin ETF", "BlackRock", "institutional capital"],
        "source_title": "SEC Filing: Bitcoin ETF Approval Notice",
        "source_url": "https://sec.gov/announcements",
    },
    {
        "ticker": "AAPL",
        "asset_type": "stock",
        "event_type": "product",
        "sentiment": 0.45,
        "magnitude": 6,
        "time_sensitivity": "near-term",
        "confidence": 0.79,
        "summary": "Apple Vision Pro launches with mixed reception. 200K preorders in first 24h, below analyst expectations of 500K.",
        "key_phrases": ["Vision Pro launch", "200K preorders", "below expectations", "mixed reception"],
        "source_title": "Apple Vision Pro Launch Day Coverage",
        "source_url": "https://reuters.com/technology",
    },
    {
        "ticker": "TSLA",
        "asset_type": "stock",
        "event_type": "scandal",
        "sentiment": -0.76,
        "magnitude": 7,
        "time_sensitivity": "immediate",
        "confidence": 0.91,
        "summary": "Tesla faces NHTSA investigation over 2.2M vehicles following autopilot-related crashes. Recall likely.",
        "key_phrases": ["NHTSA investigation", "2.2M vehicles", "autopilot crashes", "recall likely"],
        "source_title": "NHTSA Safety Investigation Report",
        "source_url": "https://nhtsa.gov/safety",
    },
    {
        "ticker": "MSFT",
        "asset_type": "stock",
        "event_type": "merger",
        "sentiment": 0.65,
        "magnitude": 8,
        "time_sensitivity": "near-term",
        "confidence": 0.85,
        "summary": "Microsoft completes $68.7B Activision Blizzard acquisition after final UK approval. Gaming revenue to double.",
        "key_phrases": ["Activision acquisition complete", "$68.7B", "UK CMA approval", "gaming revenue"],
        "source_title": "Microsoft-Activision Deal Closure Announcement",
        "source_url": "https://microsoft.com/investor",
    },
    {
        "ticker": "ETH-USD",
        "asset_type": "crypto",
        "event_type": "regulation",
        "sentiment": -0.55,
        "magnitude": 7,
        "time_sensitivity": "near-term",
        "confidence": 0.82,
        "summary": "EU MiCA regulation takes effect, requiring DeFi protocols to register. Ethereum DeFi TVL drops 12% on compliance fears.",
        "key_phrases": ["MiCA regulation", "DeFi registration", "compliance pressure", "TVL drop 12%"],
        "source_title": "EU MiCA Framework: DeFi Impact Analysis",
        "source_url": "https://europa.eu/blockchain",
    },
    {
        "ticker": "META",
        "asset_type": "stock",
        "event_type": "analyst",
        "sentiment": 0.60,
        "magnitude": 5,
        "time_sensitivity": "near-term",
        "confidence": 0.76,
        "summary": "Goldman Sachs upgrades META to Buy with $580 target, citing Reels monetization inflection and AI ad efficiency gains.",
        "key_phrases": ["Goldman upgrade", "$580 target", "Reels monetization", "AI ad efficiency"],
        "source_title": "Goldman Sachs Equity Research Note",
        "source_url": None,
    },
    {
        "ticker": "SPY",
        "asset_type": "macro",
        "event_type": "macro",
        "sentiment": -0.40,
        "magnitude": 6,
        "time_sensitivity": "near-term",
        "confidence": 0.88,
        "summary": "Fed minutes signal 'higher for longer' stance with 2 rate cuts in 2024 vs market's 6-cut expectation. Dollar strengthens.",
        "key_phrases": ["Fed minutes", "higher for longer", "2 rate cuts", "market repricing"],
        "source_title": "Federal Reserve FOMC Meeting Minutes",
        "source_url": "https://federalreserve.gov",
    },
    {
        "ticker": "AMZN",
        "asset_type": "stock",
        "event_type": "product",
        "sentiment": 0.70,
        "magnitude": 7,
        "time_sensitivity": "near-term",
        "confidence": 0.83,
        "summary": "Amazon AWS launches Bedrock Agents with multi-step reasoning. Enterprise AI spending forecasted at $4.2B incremental ARR.",
        "key_phrases": ["AWS Bedrock Agents", "enterprise AI", "$4.2B ARR", "multi-step reasoning"],
        "source_title": "AWS re:Invent 2024 Announcements",
        "source_url": "https://aws.amazon.com/blogs",
    },
    {
        "ticker": "SOL-USD",
        "asset_type": "crypto",
        "event_type": "macro",
        "sentiment": 0.80,
        "magnitude": 8,
        "time_sensitivity": "immediate",
        "confidence": 0.89,
        "summary": "Solana network processes 65,000 TPS during Firedancer validator launch, surpassing Visa throughput benchmark.",
        "key_phrases": ["65,000 TPS", "Firedancer launch", "surpasses Visa", "network milestone"],
        "source_title": "Solana Foundation: Firedancer Validator Report",
        "source_url": "https://solana.com/news",
    },
    {
        "ticker": "GOOGL",
        "asset_type": "stock",
        "event_type": "earnings",
        "sentiment": -0.30,
        "magnitude": 5,
        "time_sensitivity": "immediate",
        "confidence": 0.77,
        "summary": "Google Q3 misses ad revenue by 3%. YouTube shorts monetization lags, cloud growth slows to 22% vs 28% expected.",
        "key_phrases": ["ad revenue miss", "YouTube shorts lag", "cloud slowdown", "22% vs 28% expected"],
        "source_title": "Alphabet Q3 2024 Earnings Call",
        "source_url": "https://abc.xyz/investor",
    },
    {
        "ticker": "GLD",
        "asset_type": "macro",
        "event_type": "macro",
        "sentiment": 0.55,
        "magnitude": 6,
        "time_sensitivity": "near-term",
        "confidence": 0.80,
        "summary": "Central banks purchase record 1,037 tonnes of gold in 2023. Geopolitical de-dollarization trend accelerates.",
        "key_phrases": ["central bank buying", "record 1037 tonnes", "de-dollarization", "safe haven demand"],
        "source_title": "World Gold Council 2023 Annual Report",
        "source_url": "https://gold.org/report",
    },
    {
        "ticker": "COIN",
        "asset_type": "stock",
        "event_type": "regulation",
        "sentiment": -0.65,
        "magnitude": 8,
        "time_sensitivity": "immediate",
        "confidence": 0.92,
        "summary": "SEC files lawsuit against Coinbase alleging unregistered securities exchange operation. Stock halted pending response.",
        "key_phrases": ["SEC lawsuit", "unregistered exchange", "securities violation", "stock halted"],
        "source_title": "SEC Complaint: SEC v. Coinbase",
        "source_url": "https://sec.gov/litigation",
    },
    {
        "ticker": "NVDA",
        "asset_type": "stock",
        "event_type": "regulation",
        "sentiment": -0.50,
        "magnitude": 7,
        "time_sensitivity": "near-term",
        "confidence": 0.86,
        "summary": "US expands AI chip export restrictions to 40+ countries. NVIDIA estimates $4-5B revenue impact in H1 2024.",
        "key_phrases": ["chip export ban", "40 countries", "$4-5B impact", "H100 restrictions"],
        "source_title": "US BIS Export Control Rule Update",
        "source_url": "https://bis.doc.gov",
    },
    {
        "ticker": "DXY",
        "asset_type": "forex",
        "event_type": "macro",
        "sentiment": 0.35,
        "magnitude": 4,
        "time_sensitivity": "long-term",
        "confidence": 0.71,
        "summary": "US CPI drops to 2.9%, first time below 3% since 2021. Fed pivot probability rises to 87% per CME FedWatch.",
        "key_phrases": ["CPI 2.9%", "below 3%", "Fed pivot", "87% probability"],
        "source_title": "BLS Consumer Price Index Report",
        "source_url": "https://bls.gov/cpi",
    },
]


def get_mock_signals(count: int = None) -> list[dict]:
    """Return mock signals with staggered timestamps."""
    signals = RAW_MOCK_SIGNALS.copy()
    random.shuffle(signals)
    if count:
        signals = signals[:count]

    now = datetime.utcnow()
    for i, sig in enumerate(signals):
        sig["extracted_at"] = (now - timedelta(minutes=i * 3 + random.randint(0, 5))).isoformat()
        if "id" not in sig:
            import uuid
            sig["id"] = str(uuid.uuid4())[:8]

    return signals
